# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  chapman_identities_password: <%= ENV["CHAPMAN_IDENTITIES_PASSWORD"] %>
  chapman_identities_username: <%= ENV["CHAPMAN_IDENTITIES_USERNAME"] %>
  chapman_identities_base_url: <%= ENV["CHAPMAN_IDENTITIES_BASE_URL"] %>

development:
  <<: *common
  secret_key_base: 8e06ea0e83b4a474b0b5b9ffab4cf9c906928db69470e3d31e40d9122afad2e795b07e2937704ed3264809f0c8446b4aa953a333d134e675502f5be83623b3b6

test:
  <<: *common
  secret_key_base: ce44c3631fb2b3eab5539e9b89c08ec8eba81aae537a0d0dbe5c869d1a945f3fd8484f5b8771eaa9be2786d8cb7db2e50d4545d947abe69a8375424a5296f96d

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bugsnag_api_key: <%= ENV["BUGSNAG_API_KEY"] %>

production:
  <<: *common
  secret_key_base: 5074a0ccd8187c2f9931b5eda6ca4f9665cd100a3741dd473e1660fa536859a79c2bd0f62c9dacad9ae4a8c378bd9a781e3c123b0b752a83bd43957bd5901f0c
  bugsnag_api_key: <%= ENV["BUGSNAG_API_KEY"] %>
